account:
  type: string
  default: ''
  description: Matomo account name
site_id:
  type: string
  default: ''
  description: Site ID associated with account (e.g. 1, 2, etc.)
exclude_groups:
  type: string
  default: ''
  description: Comma separated list of groups to exclude from tracking such as admins, staff.
user_id_tracking:
  type: string
  default: ''
  description: An indentifying field name on the current user object such as id, username or external_id.
subdomain_tracking:
  type: bool
  default: false
  description: Track visitors across main domain & subdomains, assuming discourse is on a subdomain.
